data_loader:
  batch_size: 39
gpu_config:
  gpu_name: 0
  use_gpu: true
output_size: 256
period: 8
model:
  if_pre_train: true
  n_channels: 1
  class_num: 3
  step: 1
  path:
optimizer:
  lr: 0.0005
  method: Adam
  weight_decay: 1.0e-08
path:
  data_path: 
  save_path:
csv_path:
  train: 
  val: 
  ratios: 
train_param:
  Epoch: 20
