data_loader:
  batch_size: 39
gpu_config:
  gpu_name: 0
  use_gpu: true
output_size: 256
period: 8
model:
  if_pre_train: true
  n_channels: 1
  class_num: 3
  path: 'C:\Users\nbs49\Desktop\pytorch_segmentation\models\model_8.pth'
optimizer:
  lr: 0.0005
  method: Adam
  weight_decay: 1.0e-08
path:
  data_path: 'C:/Users/nbs49/Desktop/pytorch_segmentation/data/dataset.hdf5'
  save_path: 'C:/Users/nbs49/Desktop/pytorch_segmentation/data/new_model'
csv_path:
  train: 'C:/Users/nbs49/Desktop/pytorch_segmentation/data/patches.csv'
  val: 'C:/Users/nbs49/Desktop/pytorch_segmentation/data/val.csv'
  ratios: 'C:/Users/nbs49/Desktop/pytorch_segmentation/data/ratios.csv'
train_param:
  Epoch: 60
